services:
  mysql:
    container_name: rinha_backend
    image: mysql
    restart: always

    env_file:
      - backend/.env

    ports:
      - '3306:3306'

  redis:
    image: redis
    ports:
      - '6379:6379'
